### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by proudparrot2** [Fluxpuck/Hyper#2]
Is there supposed to be commands here?

**Comment by Fluxpuck** [comment]
The branch names disclose what it's been worked on, and give you an indication of what is to be done.

**Comment by proudparrot2** [comment]
Yes I only see some test commands. Are there supposed to be others?

**Comment by Fluxpuck** [comment]
There will be in the future. Currently, we are working on the main frame of the bot (see the branches), after which we will continue transferring and implementing the commands.

**Comment by Bartekturbo** [comment]
hi

**Comment by Bartekturbo** [comment]
this is a good bot
